DROP DATABASE IF EXISTS dsw;
CREATE DATABASE dsw;

USE dsw;

CREATE TABLE IF NOT EXISTS tb_users (
    id int AUTO_INCREMENT PRIMARY KEY, 
    username VARCHAR(255), 
    email VARCHAR(255), 
    password VARCHAR(255), 
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tb_tasks (
    id int AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30),
	description VARCHAR(255),
	progress INT NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT NOW()
);